FROM nginx

# Copy Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Create directory for SSL certificates
RUN mkdir -p /etc/nginx/ssl

# Copy SSL certificate files
COPY ssl_certificate.crt /etc/nginx/ssl/ssl_certificate.crt
COPY ssl_certificate_key.key /etc/nginx/ssl/ssl_certificate_key.key

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"];